- name: Install prerequisites (Amazon Linux)
  become: true
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: Add Docker repository
  become: true
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  become: true
  yum:
    name: docker
    state: latest

- name: Start Docker service
  become: true
  service:
    name: docker
    state: started
    enabled: true

- name: Create app directory
  become: true
  file:
    path: /opt/app
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0755'

- name: Copy application files (optional if you're using volumes)
  become: true
  copy:
    src: ./app/
    dest: /opt/app/
    mode: '0755'
  when: app_dir is defined  # Optional: add var check if needed

- name: Run Web App Container
  become: true
  docker_container:
    name: hello-app
    image: nginx
    state: started
    ports:
      - "80:80"
    # # command: "node /app/server.js"
    # volumes:
    #   - "/opt/app:/app"


- name: Ensure pip3 is installed (Amazon Linux / RHEL)
  become: yes
  yum:
    name: python3-pip
    state: present
  when: ansible_os_family == "RedHat"

- name: Ensure pip3 is installed (Debian/Ubuntu)
  become: yes
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"
#### Deploy Flask app
- name: Upload Flask app
  copy:
    src:  ../../../../app/app.py
    dest: /home/ec2-user/app.py
    mode: '0755'

- name: Install Flask
  pip:
    name: flask
    executable: pip3

- name: Run Flask app
  shell: nohup python3 /home/ec2-user/app.py > flask.log 2>&1 &
  args:
    executable: /bin/bash