version: "3"

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # loki:
  #   image: grafana/loki:2.9.1
  #   ports:
  #     - "3100:3100"
  #   command: -config.file=/etc/loki/loki-config.yml
  #   volumes:
  #     - ./loki/loki-config.yml:/etc/loki/loki-config.yml
      # - ./loki:/tmp/loki

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana-storage:

