    # This goes inside roles/ubuntu-webserver/tasks/main.yml

    - name: Install apt packages
      apt:
        name:
          - docker.io
          - python3-pip
        state: present
        update_cache: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Compose 
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version  

    - name: Create app directory
      file:
        path: /opt/app
        state: directory
        owner: azureuser
        group: azureuser
        mode: '0755'

    - name: Run NGINX container
      docker_container:
        name: hello-nginx
        image: nginx
        state: started
        ports:
          - "80:80"

    - name: Ensure pip3 is installed
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Upload Flask app
      copy:
        src: ../../../../app/app.py
        dest: /home/azureuser/app.py
        mode: '0755'

    - name: Install Flask
      pip:
        name: flask
        executable: pip3

    - name: Run Flask app
      shell: nohup python3 /home/azureuser/app.py > flask.log 2>&1 &
      args:
        executable: /bin/bash

    - name: Copy docker-compose.yml to remote server
      copy:
        src:  ../../../../monitoring/docker-compose.yml
        dest: /home/{{ ansible_user }}/docker-compose.yml
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0644'

    - name: Run docker-compose up -d
      command: docker-compose up -d
      args:
        chdir: /home/{{ ansible_user }}
