name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6 
      - name: Terraform Apply AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }} 
        run: |
          cd terraform/aws
          terraform init
          # terraform apply -auto-approve

      # - name: Terraform Apply IBM
      #   run: |
      #     cd terraform/ibm
      #     terraform init
      #     terraform apply -auto-approve

      - name: Run Ansible for AWS
        run: ansible-playbook -i ansible/inventory_aws.ini ansible/playbook.yml

      # - name: Run Ansible for IBM
      #   run: ansible-playbook -i ansible/inventory_ibm.ini ansible/playbook.yml
